package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Elegant Dark Colors (Dark / Light)
val ElegantDarkPrimaryDark = Color(0xFFD0BCFF)
val ElegantDarkSecondaryDark = Color(0xFFCCC2DC)
val ElegantDarkTertiaryDark = Color(0xFFEFB8C8)
val ElegantDarkBackgroundDark = Color(0xFF141218)
val ElegantDarkSurfaceDark = Color(0xFF1D1B20)
val ElegantDarkSurfaceVariantDark = Color(0xFF2B2930)
val ElegantDarkOnPrimaryDark = Color(0xFF381E72)
val ElegantDarkOnSecondaryDark = Color(0xFF332D41)
val ElegantDarkOnBackgroundDark = Color(0xFFE6E1E5)
val ElegantDarkOnSurfaceDark = Color(0xFFE6E1E5)
val ElegantDarkOnSurfaceVariantDark = Color(0xFFCAC4D0)
val ElegantDarkPrimaryContainerDark = Color(0xFFE8DEF8)
val ElegantDarkOnPrimaryContainerDark = Color(0xFF1D192B)
val ElegantDarkSecondaryContainerDark = Color(0xFF4A4458)
val ElegantDarkOnSecondaryContainerDark = Color(0xFFE8DEF8)

val ElegantDarkPrimaryLight = Color(0xFF6750A4)
val ElegantDarkSecondaryLight = Color(0xFF625B71)
val ElegantDarkBackgroundLight = Color(0xFFFEF7FF)
val ElegantDarkSurfaceLight = Color(0xFFF7F2FA)
val ElegantDarkSurfaceVariantLight = Color(0xFFE7E0EC)

// Cosmic Blue Colors (Dark / Light)
val CosmicBluePrimaryDark = Color(0xFF4DA3FF)
val CosmicBlueSecondaryDark = Color(0xFF9CCAFF)
val CosmicBlueBackgroundDark = Color(0xFF0F172A)
val CosmicBlueSurfaceDark = Color(0xFF1E293B)
val CosmicBluePrimaryLight = Color(0xFF0061A4)
val CosmicBlueSecondaryLight = Color(0xFF535F70)
val CosmicBlueBackgroundLight = Color(0xFFF8FAFC)
val CosmicBlueSurfaceLight = Color(0xFFFFFFFF)

// Mystic Purple Colors (Dark / Light)
val MysticPurplePrimaryDark = Color(0xFFD3BBFF)
val MysticPurpleSecondaryDark = Color(0xFFE2DFFF)
val MysticPurpleBackgroundDark = Color(0xFF120024)
val MysticPurpleSurfaceDark = Color(0xFF21103A)
val MysticPurplePrimaryLight = Color(0xFF6B4EA2)
val MysticPurpleSecondaryLight = Color(0xFF625B71)
val MysticPurpleBackgroundLight = Color(0xFFFFF7FF)
val MysticPurpleSurfaceLight = Color(0xFFF6EEFF)

// Sunset Orange Colors (Dark / Light)
val SunsetOrangePrimaryDark = Color(0xFFFFB59B)
val SunsetOrangeSecondaryDark = Color(0xFFE7BDB1)
val SunsetOrangeBackgroundDark = Color(0xFF1C0D02)
val SunsetOrangeSurfaceDark = Color(0xFF2C190D)
val SunsetOrangePrimaryLight = Color(0xFF9C4325)
val SunsetOrangeSecondaryLight = Color(0xFF77574E)
val SunsetOrangeBackgroundLight = Color(0xFFFFFBFF)
val SunsetOrangeSurfaceLight = Color(0xFFFCEAE5)

// Mint Green Colors (Dark / Light)
val MintGreenPrimaryDark = Color(0xFF66DBB2)
val MintGreenSecondaryDark = Color(0xFFB4CCBF)
val MintGreenBackgroundDark = Color(0xFF0A1F16)
val MintGreenSurfaceDark = Color(0xFF162E23)
val MintGreenPrimaryLight = Color(0xFF006C4F)
val MintGreenSecondaryLight = Color(0xFF4F6357)
val MintGreenBackgroundLight = Color(0xFFF0FDF4)
val MintGreenSurfaceLight = Color(0xFFE8F5E9)
